# Automated Windows and Linux testing using appveyor.com
# https://ci.appveyor.com/projects

version: '{branch}-{build}'

image:
- Ubuntu1804
- Visual Studio 2015
- Visual Studio 2017

platform:
  - x86
  - x64

for:
  - matrix:
      only:
        - image: Ubuntu1804
          platform: x86
    environment:
      CFLAGS: "-Wall -Wextra -pedantic -Werror -O1 -g -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
      CXXFLAGS: "-Wall -Wextra -pedantic -Werror -O1 -g -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
    install:
      - sudo apt install --yes cppcheck
    build_script:
      - cmake . -DCMAKE_BUILD_TYPE=Debug
      - make VERBOSE=1
    test_script:
      - cppcheck . --error-exitcode=1 --force -i doc
      - ./tester
      - ./benchmark_branchfree

  - matrix:
      only:
        - image: Ubuntu1804
          platform: x64
    environment:
      CFLAGS: "-Wall -Wextra -pedantic -Werror -O1 -g -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
      CXXFLAGS: "-Wall -Wextra -pedantic -Werror -O1 -g -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
    install:
      - sudo apt install --yes cppcheck
    build_script:
      - CC=clang CXX=clang++ cmake . -DCMAKE_BUILD_TYPE=Debug
      - make VERBOSE=1
    test_script:
      - cppcheck . --error-exitcode=1 --force -i doc
      - ./tester
      - ./benchmark_branchfree

  - matrix:
      only:
        - image: Visual Studio 2015
          platform: x86
    environment:
      CFLAGS: "/DLIBDIVIDE_ASSERTIONS_ON"
      CXXFLAGS: "/DLIBDIVIDE_ASSERTIONS_ON"
    build_script:
      - cmake . -G "Visual Studio 14 2015"
      - cmake --build . --config Release
    test_script:
      - cd Release
      - tester.exe
      - benchmark_branchfree.exe

  - matrix:
      only:
        - image: Visual Studio 2015
          platform: x64
    environment:
      CFLAGS: "/DLIBDIVIDE_ASSERTIONS_ON"
      CXXFLAGS: "/DLIBDIVIDE_ASSERTIONS_ON"
    build_script:
      - cmake . -G "Visual Studio 14 2015 Win64"
      - cmake --build . --config Release
    test_script:
      - cd Release
      - tester.exe
      - benchmark_branchfree.exe

  - matrix:
      only:
        - image: Visual Studio 2017
          platform: x86
    build_script:
      - cmake . -G "Visual Studio 15 2017"
      - cmake --build . --config Release
    test_script:
      - cd Release
      - tester.exe
      - benchmark_branchfree.exe

  - matrix:
      only:
        - image: Visual Studio 2017
          platform: x64
    environment:
      CFLAGS: "/W3 /WX /DLIBDIVIDE_ASSERTIONS_ON"
      CXXFLAGS: "/W3 /WX /DLIBDIVIDE_ASSERTIONS_ON"
    build_script:
      - cmake . -G "Visual Studio 15 2017 Win64"
      - cmake --build . --config Release
    test_script:
      - cd Release
      - tester.exe
      - benchmark_branchfree.exe
